### ISSUE TITLE
Instant browser crash when pressing on the upper facbook icons inbox and notifications

### ISSUE THREAD

**Issue by SJ-Diamond** [QupZilla/qupzilla#1426]
Browser instantly crashes when pressing these buttons on Facebook.  Error code is the following one under Windows 8:

Name of misapplication: qupzilla.exe, version: 1.6.6.0, time stamp: 0x5370cca1 
Name of the faulty module: QtWebKit4.dll, version: 4.10.0.0, time stamp: 0x51783c0c 
Exception code: 0xc0000005 
Error offset: 0x001b3720 
ID of the faulty process: 0x364 
Start time of misapplication: 0x01cf9c843a866a1d 
Path of the faulty application: C: \ Program Files (x86) \ QupZilla \ qupzilla.exe 
Path of the faulty module: C: \ Program Files (x86) \ QupZilla \ QtWebKit4.dll 
Report ID: 82df0f5d-0877-11E4-8272-8086f2debec5 
Full name of the defective package: 
Application ID, which is relative to the defective package:

**Comment by terids** [comment]
So do we have to wait for qtwebkit to resolve the issue? And if it does get fixed how long before qt is updated for the windows version of qupzilla?
Application version: 1.8.6
Qt version: 4.8.5
WebKit version: 537.21

**Comment by Thunderpig72** [comment]
Feels like a qtwebkit fork would be a good idea.

**Comment by The-Compiler** [comment]
> Feels like a qtwebkit fork would be a good idea.

The reason QtWebKit gets little love is because there are too few people working on it, and Qt's efforts are probably concentrated on the successor, QtWebEngine.

"There is too little manpower" isn't really a problem which can be solved by forking something - quite the contrary, actually.

*Contributing* to QtWebKit, however, would be a good idea!
