### ISSUE TITLE
Computer freezes confirming new contact in LinkedIn social network using Qupzilla

### ISSUE THREAD

**Issue by osinclair** [QupZilla/qupzilla#1591]
Environment:
Kubuntu Linux 14.10 w KDE 4.14.4, Qupzilla 8.1.5 from Qupzilla ppa but the behaviour has been noted since several versions of both Kubuntu and Qupzilla

1. Recieve email with connection request from LinkedIn OR open LinkedIn in Qupzilla
2. click on confirm in email (opens browser) OR in Qupzilla
3. computer goes into total freeze while disk is spinning like mad, only altgr+prtscr REISUB will reboot it

Expected behaviour: 
1. click on confirm new contact
2. new contact webpage opens with details on new contact, connections etc
3. computer continues to work as usual

**Comment by JHooverman** [comment]
Could you please check, if your issue is reproducible with the [arora-browser](http://code.google.com/p/arora/) or with [QtTestBrowser](http://cloud.qupzilla.com/public.php?service=files&t=e05650e3f9cf53343efcda2d3a01f1b1)?

Please have a look [here](https://github.com/QupZilla/qupzilla/wiki/Bug-Reports#4-please-provide-any-additional-information-below) as well.

Thank you for your cooperation.

**Comment by osinclair** [comment]
JHooverman - I will do as soon as I get a new invite

**Comment by osinclair** [comment]
I ended up using Rekonq instead of Arora as for whatever reason Arora did not play nicely for me. And yes I get the same result

**Comment by nowrep** [comment]
This is issue with old WebKit that comes with QtWebKit.
This will be fixed with QtWebEngine.
