### ISSUE TITLE
Images On Alot Of Sites Not Appearing...

### ISSUE THREAD

**Issue by ghost** [QupZilla/qupzilla#1638]
Hi,

I originally started this out for deviantart.com, but then realizing after using 1.8.6 I am just completly shocked at how many sites I'm going to with the images broke on them.

I never used 1.8.6 when it came out, but I just now started to play with it and this situation is just not useable at all for a browser.

I'm not sure if there's some feature of QupZilla causing this which seems odd to do so.

Below is a screen shot of deviantart.com as an example.

![da](https://cloud.githubusercontent.com/assets/11289036/7133354/3cfbfe90-e22e-11e4-811a-b1f843a4dea3.jpg)

Today I just went to 5 sites and images were broken on 3 of them. So for a figure, roughly 3 out of every 5-6 sites I'm going to I'm seeing this problem... :(

Even here on GitHub the image I attached I can't see it with QupZilla. 

I compiled 1.8.6 with QT 5.4.1 in Linux...

**Comment by JHooverman** [comment]
I am not able to reproduce your issue, see

![dev1](http://i.imgur.com/yQtdQpS.png)

Which user agent do you have configured?

**Comment by meuwe** [comment]
Everything is default, I just started Qupzilla and imported my bookmarks, this is all...

So this is happening on the ```First``` start, for the ```First``` time with QupZilla...

**Comment by meuwe** [comment]
Ok I recompiled over with QT 5.4.1 and stilll no images, actually this pretty much happens on every site... :(

I also have QT4.8.5 installed and I compiled this time with QT4 and the images work.

This seems to be a QT5 issues here?

Also compling with ```qmake``` also works on systems that only have QT4, if you only have QT4 you don't need qmake-qt4, might want to change that in the readme, since it's not technically correct.

**Comment by nowrep** [comment]
Make sure you have installed all needed Qt imageplugins.
