### ISSUE TITLE
html5 mp3 audio not working

### ISSUE THREAD

**Issue by FedeDP** [QupZilla/qupzilla#1684]
Hi!
I'm trying out qupzilla 1.9.0 witn qtwebengine, and i have this strange issue.
I can watch html5 videos, but i cannot listen to mp3 (eg from google play music).
I have all gstreamer 1.0 packages (archlinux with qt5.5 here).
html5test shows i've got no aac and mp3 support.
I remember this was working (last time i checked, probably months ago), any idea?

Thank you very much for your efforts!

**Comment by cranes-bill** [comment]
Did you tried some other source(s) and browser(s) and what's going on, when you open any audio file directly in Qupzilla? [**Here**](http://voix.larousse.fr/anglais/129487ang2.mp3) is an test source for example.
Did you tried with fresh profile? 
Do you have flash player installed on your system?

_By the way, perhaps the title needs a small correction!_  :stuck_out_tongue_winking_eye:

**Comment by FedeDP** [comment]
Damn sorry for the title :D 
The profile is fresh; i have chromium-pepper-flash installed, and in chromium everything works. 
In otter-browser it does not work, so i guess it can be a problem with gstreamer or webengine, correct me if i'm wrong.
Play music just keeps saying i need flashplayer to listen to my music (even if i obviously have the html5 audio option ON).
And...btw qupzilla and otter-browser make me download your test source :)

**Comment by cranes-bill** [comment]
The reason to ask you about Flashplayer is because that, when i played a flash video sometimes ago, then Qupzilla gets trying to play any video with Flashplayer even it was not already on the system, until i cleaned the cache. Run Qupzilla from the terminal of the following way: `HOME=/tmp Qupzilla` and see if something will change! Also you might try to uncheck: **__Menu » Navigation:__** :ballot_box_with_check: **Allow Netscape (flash plugin)** (The above has no effect to me)
P.S: Sorry for my bad English! :flushed:

**Comment by FedeDP** [comment]
I tried both method, but it is still not working...
Thanks anyway :)

**Comment by cranes-bill** [comment]
Sorry, it seems the problem is in the plugins. Maybe in any _Archlinux forum_ might helps.

**Comment by FedeDP** [comment]
Yes...it seems the problem isn't in qt5-webengine either (i don't even know if it has something to do, to be honest), because otter-browser with qtwebkit isn't working still.
I'll ask for help on archlinux forum, thanks for your time :)

**Comment by nowrep** [comment]
I think you need non-free codecs for Chromium ffmpeg. In any case, this is upstream issue.
