### ISSUE TITLE
Qupzilla as starting browser.

### ISSUE THREAD

**Issue by keira2** [QupZilla/qupzilla#1697]
I am using firefox and qupzilla.how can I set qupzilla as my starting browser ?

Robert 
the NETHERLANDS

**Comment by nowrep** [comment]
What is your OS?

**Comment by keira2** [comment]
The linux system: XUBUNTU

Op 30-08-15 om 21:35 schreef David Rosca:

**Comment by nowrep** [comment]
In that case you need to set it as default browser somewhere in XFCE desktop settings.

**Comment by cranes-bill** [comment]
Copy/Paste the following on the terminal, should work! (may needs the session log out)
```
if [ -z "$(grep firefox ~/.local/share/applications/mimeapps.list )" ]
then
cat <<EOF >> ~/.local/share/applications/mimeapps.list
x-scheme-handler/http=qupzilla.desktop
x-scheme-handler/https=qupzilla.desktop
EOF
else
sed -i 's/firefox/qupzilla/g' ~/.local/share/applications/mimeapps.list
fi

```

**Comment by keira2** [comment]
The second command after "then",is that 1 command ?

**Comment by cranes-bill** [comment]
Sorry, my English is very bad, so i fail to understand your question!
You must copy and paste all the code!
You might also edit the file: `~/.local/share/applications/mimeapps.list` in any text editor, or just to use xdg-mime or xdg-settings command.
Otherwise, try some of the following graphic tools (*i'm not sure wich is the correct one in this case*):

* /usr/bin/xfce4-settings-manager
* /usr/bin/xfce4-settings-editor
* /usr/bin/xfce4-mime-settings

**Comment by keira2** [comment]
Hi Cranes-bill,

Thank you for your advice, it worked
