### ISSUE TITLE
[POLL] Change name to Qupzilla

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#1765]
This is a continuation of issue #1659.  Would you like this project to be renamed from QupZilla to Qupzilla? Vote here http://strawpoll.me/6022167

**Comment by JHooverman** [comment]
QupZilla

@GreenLunar: Will you count all the votes?

**Comment by GreenLunar** [comment]
There are 3 votes for Qupzilla:
@elioqoshi
@GreenLunar
@ke7ofi

**Comment by elioqoshi** [comment]
Yep, Qupzilla looks more approachable.

**Comment by GreenLunar** [comment]
@JHooverman, Done.

I think you are able to edit the first comment because your status is Collaborator.

**Comment by JHooverman** [comment]
@GreenLunar: I would like to add, that the final decision about changing the name slightly can only be done by @nowrep.

**Comment by nowrep** [comment]
Exactly, also there is an issue with this poll as (apart from that GitHub does not have "real" polls) only registered users can vote.

**Comment by elioqoshi** [comment]
Can we do a Google Form?

**Comment by ke7ofi** [comment]
http://strawpoll.me/6022167

**Comment by nowrep** [comment]
Yep, this one is better. I will link it from blogpost.

**Comment by pejakm** [comment]
> http://strawpoll.me/6022167

Any chance you can change that font to something more clearly visible?

**Comment by ke7ofi** [comment]
@pejakm Sorry, it's a preset thing meant for quick polls like this one. I have no idea why they wanted something so ugly.

**Comment by GreenLunar** [comment]
> @GreenLunar: I would like to add, that the final decision about changing the name slightly can only be done by @nowrep.

Certainly so.  I am doing it to put pressure on @nowrep ;)

**Comment by ke7ofi** [comment]
@GreenLunar I'm not sure that “putting pressure” is the right way to think about it. It's @nowrep's project, and all we're (I'm, at least) doing is trying to show what the community, to whatever extent that exists, prefers.

**Comment by elioqoshi** [comment]
It's a figure of speech, I suppose. No need to take it literally :)

**Comment by ke7ofi** [comment]
@elioqoshi I know, but it can also indicate mindset.

**Comment by elioqoshi** [comment]
I don't think that should be judgmental. Anyway, back on topic.

**Comment by cranes-bill** [comment]
Such a pointless issue......
Furthermore, the vote can be manipulated.

**Comment by GreenLunar** [comment]
> Such a pointless issue......

Not really, this is a matter in marketing QupZilla; otherwise, it would not even have a logo.

>  Furthermore, the vote can be manipulated.

This is true.

> @GreenLunar I'm not sure that “putting pressure” is the right way to think about it.

I stand corrected, you are correct.

Perhaps getting @nowrep's attention into this issue and persuading him to take a decision to rename this project to Qupzilla.

**Comment by ke7ofi** [comment]
> Furthermore, the vote can be manipulated.

That implies that people care enough about the name of a browser to resort to dishonesty, which (I hope) is unlikely.

**Comment by GreenLunar** [comment]
@Martii, please kindly submit your opinion on this matter, if you may.

**Comment by Martii** [comment]
Well... it's more pleasing on the eye with a lowercase z ... however this may break linkage down the road as I usually match exact casing for projects names.

So @GreenLunar your start of the docs at https://openuserjs.org/about/Qupzilla will return a 404 rather than what it is now [with the uppercase](https://openuserjs.org/about/QupZilla).

So a tally here based of this criteria... +1, -1 yields me at 0 with a lean towards not breaking someones reference of pages that are case-sensitive which can affect SEO e.g. if someone has made a link on a non-comment-editable site *(sound familiar? ;)* ... total -0.

Perhaps with some more phonetic pronunciation declaration, the history of where the name came from *(dark regions of inner thought don't count and I can guess that `Q` implies Qt ;)*, and perhaps a statistical analysis on how the en-US letter Z affects the human psyche... it might sway me out of the zero zone.

Outside of the voting it does seem to me to be a minor thing to reconsider since the projects [first commit](https://github.com/QupZilla/qupzilla/commit/b23ed87b872c6c773210b7e8ff6456d9ce2f407c) is from early 2011... perhaps it seems a little late for analysis on the human interaction factor to me.

**Comment by ke7ofi** [comment]
I like Qz a lot. Neat idea, but people will inevitably mispronounce it. Fortunately, this is the internet, so that doesn't matter.

**Comment by GreenLunar** [comment]
By the way, since GH has added "reaction" (thumbs up/down), similarly to GitLab, we can directly vote here.

**Comment by ke7ofi** [comment]
Let's change the name of the issue to "Change name to Qupzilla", then.

**Comment by MailYouLater** [comment]
I like it better as QupZilla.
It makes it stand out a bit from the 'crowd' of other '&hellip;zilla' programs out there, while still allowing it to 'fit&nbsp;in' along with them.

I've added a :-1: to the opening post to reflect this.

**Comment by elioqoshi** [comment]
I'm still for Qupzilla

**Comment by sveinki** [comment]
Sorry to be late:
As a translator I have some issues with QupZilla/Qupzilla as a common name for the browser. At least in my language (Icelandic), it's a bit of a 'tongue twist' using the full name in a sentence or in menus, would be more natural talking about the 'QZ-browser' or 'browse with QZ'. Yet it would be perfectly valid for the full name to appear in dialogs like 'About the QZ-browser' and in help/wiki and such.
What do you think about this perspective?

**Comment by GreenLunar** [comment]
How does QupZilla sounds in Icelandic?

There are some brands that begin with a certain letter, and are pronounced without that letter (e.g. __Xu__ would be pronounced as __Zu__), so you might want to resort to this solution.

**Comment by sveinki** [comment]
It really does sound 'foreign' ... ;-)

Neither Q nor Z are part of the Icelandic alphabet, so words containing them are treated as proper names (like brands). Transliterating them (e.g. 'KupSilla') is not a solution, because they rarely obey the rythm of the language; translating them or inventing a new localized name is normally a no-no which can lead to confusion and frustration e.g. when looking for advanced help on the web.
A simple acronym is often an easier way to avoid repeating too often something hard to pronounce, and anyway the QupZilla word does not hold any meaning in itself (although for some nerds it does contain historical references). Nevertheless QupZilla is totally valid as a brand.

So I was just speculating whether people would oppose the use of 'QZ-browser' or 'browse with QZ' inside dialogs or other content (e.g. Help). One does not modify branding, unless having no other solutions.
