### ISSUE TITLE
PythonScrypts

### ISSUE THREAD

**Issue by selfus** [QupZilla/qupzilla#1812]
Would like to leave a suggestion for a future feature for qupzilla.
Create an add-on that lets you use python scrypts, something like greasemonkey, but for python

**Comment by ke7ofi** [comment]
JS is pretty standard for the web. It hasn't been developed for a while, but have you seen Luakit?

**Comment by The-Compiler** [comment]
shameless plug,  now that luakit got mentioned: I'm also working on [qutebrowser](http://www.qutebrowser.org/) since a while. It's a vim-like browser too, but written in Python (and using QtWebKit, and soon, QtWebEngine).

There's no plugin API yet, but that's one of my main todo's after QtWebEngine support.

**Comment by ke7ofi** [comment]
This is getting progressively farther from QupZilla, but what I'm really looking for is something like Textadept (I don't like vi/Vim.), but built around QtWebEngine instead of Scintilla. I suspect I'll have to write that myself, though, and I don't have the skills at this point.

**Comment by nowrep** [comment]
The thing with JS is that every API is already there, so you can modify everything on page as you like. If the "userscripts" were written in Python, there would need to be the same API available (or just a possibiliy to call JS code, which kind of defeats the puprose ...).

So this is not going to happen.
