### ISSUE TITLE
Crash when laptop lid is closed

### ISSUE THREAD

**Issue by hjek** [QupZilla/qupzilla#1832]
Qupzilla (1.8.9) crashes when laptop lid is closed (on Ubuntu Wily x86-64). Happens every time lid is closed, so very easy to reproduce.
Crash log attached:
[Crash-2016-01-13T12:13:06.txt](https://github.com/QupZilla/qupzilla/files/88808/Crash-2016-01-13T12.13.06.txt)

**Comment by The-Compiler** [comment]
This is probably [QTBUG-42985](https://bugreports.qt.io/browse/QTBUG-42985) or one of the related bugs. Most of them are fixed in Qt 5.5 and some more in 5.6 - unfortunately Ubuntu prefers to stick with outdated versions, 5.4 in the case of Ubuntu Wily.

You'd need to open a bug report with Ubuntu and ask them to backport those fixes. If I remember correctly, Debian didn't backport them all because too much changed.

**Comment by hjek** [comment]
looks like that QT bug indeed.
