### ISSUE TITLE
Weak Cipher Being Used?

### ISSUE THREAD

**Issue by Geyup** [QupZilla/qupzilla#1840]
I'm using 1.8.9 in Linux, with WebKit version 538.1, compiled against QT5 5.5.1.

I've been looking through the options, `qupzilla:config` shows `DisableWeakCiphers` true and it's checked in the GUI.

At a site `slackbuilds.org` I have to enable in Firefox; `security.ssl3.dhe_rsa_aes_128_sha` in order for the site to load, which is a weak/insecure cipher, and I noticed that QupZilla loads the site without a problem, so it made me wonder if a weak cipher is being used here?

hmm

**Comment by Geyup** [comment]
I contacted the site and they've changed the site, which ranks A with ssllabs.

The only way I could access the site with Firefox, was by having one of the weak cihphers enabled.

security.ssl3.dhe_rsa_aes_128_sha
security.ssl3.dhe_rsa_aes_256_sha

This makes me worried that QupZilla uses these weak cihpers, otherwise how could the site of loaded?

**Comment by cranes-bill** [comment]
https://www.ssllabs.com/ssltest/viewMyClient.html
https://weakdh.org/
https://www.howsmyssl.com/

**Comment by Geyup** [comment]
My question is, I could only access the sit with Firefox using the weak ciphers, so then how is QupZilla is loading it, if it's not using weak ciphers?

thanks

**Comment by JHooverman** [comment]
I confirm the results given by @Geyup.

My system:
Application version: 1.8.9
Qt version: 5.5.1
WebKit version: 538.1
Platform: openSUSE Tumbleweed (Linux)
openssl-1.0.2e
gnutls-3.4.8
DisableWeakCiphers=true

In case, that the mentioned ciphers are weak, they should be added to the blacklist. This will prevent them from being used, if `DisableWeakCiphers` is checked.

This issue is related to #1278 and #1428.
