### ISSUE TITLE
Allow phonon-vlc backend

### ISSUE THREAD

**Issue by taohansen** [QupZilla/qupzilla#1844]
I don't want to use gstreamer and I shouldn't have to. Arch Linux offers the choice of phonon-vlc or phonon-gstreamer backends (or both). I'd like to be able to make the choice of phonon-vlc only and still be able to use QupZilla to watch videos, etc.

**Comment by kkofler** [comment]
(Disclaimer: I am only a downstream packager for QupZilla, but I can answer this anyway.)

Sorry, but this is not possible. QtWebKit uses GStreamer directly, not through Phonon. QtWebKit used to use QtMultimedia in the distant past (but never Phonon), but switched to using GStreamer directly because this allowed sharing the code with WebKitGTK and cutting the unnecessary middleman.

QupZilla 2 will instead use QtWebEngine, which uses FFmpeg directly instead (by default, a version bundled with QtWebEngine, though it may be compiled/linked against a system FFmpeg library); that may or may not be more to your liking. But it does not use Phonon nor libvlc either.

There isn't really anything the QupZilla developer (@nowrep) can do about this. It is the result of design decisions in the underlying web engines.

**Comment by nowrep** [comment]
Exactly as @kkofler said.
