### ISSUE TITLE
Flash bug in V2.0

### ISSUE THREAD

**Issue by IsaiahPatton** [QupZilla/qupzilla#1912]
Qupzilla 2.0 with Flash installed and enabled in Qupzilla does not work because Qupzilla uses Chromium and Chromium has flash disabled all the time

Photo of flash enabled in Qupzilla:
![qupflash](https://cloud.githubusercontent.com/assets/16439221/14220291/1406fb3c-f82d-11e5-85d9-823d7e6b2898.PNG)

Photo of flash not working:
![qupflash2](https://cloud.githubusercontent.com/assets/16439221/14220290/14045a8a-f82d-11e5-8d6b-cb297cf715b7.PNG)
When I press "get flash player" button (in last photo) it says Chromium has flash disabled

**Comment by nowrep** [comment]
You need to install pepperflash.

**Comment by Martii** [comment]
Ref:
* https://aur.archlinux.org/packages/chromium-pepper-flash/

**Comment by Kizza00232Jera** [comment]
I still have problem with flash, could you help me by posting all steps with that pepperflash, I don't know to add it in qupzilla, to download it? I've downloaded flash20.tar.xz but I don't know where to put that file, or how to run it in qupzilla, yep I need more help, just wanna play some games, but I can't play them anymore..

**Comment by cranes-bill** [comment]
Which system?

**Comment by Martii** [comment]
I see this in a web search... might be useful to link into here since a search here on the repo yields zero answers. :)

* https://doc-snapshots.qt.io/qt5-5.6/qtwebengine-platform-notes.html

I'll give this a try later today and see if it works... may have to install Chromium, or a piece of it, though from the looks of it.
