### ISSUE TITLE
Font settings for new users default to the first font on the list

### ISSUE THREAD

**Issue by ugjka** [QupZilla/qupzilla#1955]
Steps to reproduce:

Create a new user in qupzilla
Check font settings in qupzilla
All fonts set to the first font on the list (AkrutiMal1 in my case)

------------
My system
ChakraOS distro

Qupzilla -2.0.0
Qt - 5.6.0
Platform - Linux

**Comment by Martii** [comment]
This was similar to what was happening under ArchLinux *(see https://github.com/QupZilla/qupzilla/issues/1902#issuecomment-203883152)* but my current distro is not doing anything like this since I received the Qt5.6 libs. Have to redo that ArchLinux VM, with a snapshot this time, as it's unusable with one of it's updates so it got happily deleted... next week though.

**Comment by demmm** [comment]
This is only an issue if the users home dir is clean from any Qupzilla settings, seems your current distro sets some configurations already.  Just remove all in ~/ for Qupzilla, you will see the font selection will be set to the first font available on your system according to the alphabetical order.

**Comment by Martii** [comment]
@demmm 
Thanks. That's usually what I do first thing is remove any trace of `.` files related to QupZilla... still main distro chooses DejaVu family *(first time install)* and ArchLinux chooses whatever. When I redo the VM sometime next week with ArchLinux I'll take a clean snapshot too.
