### ISSUE TITLE
Keyboard shortcuts to switch tabs

### ISSUE THREAD

**Issue by skalee** [QupZilla/qupzilla#1962]
Hi!

I am aware of `Alt+[0-9]` shortcuts. But they're not very helpful when you open more than 10 tabs. I believe there should be some key to switch between neighbouring tabs, to the next one or to the previous one. I've found a commit 683ec42736e63b6bed499d4666d3483b59ae1d92 which is supposed to solve that (with `1` and `2` keys), but these aren't working any more (QZ 1.8.9, OS X 10.10.5).

I believe it'd be great to have these keys back. Alternatively, another combination could be used. On Mac browsers, it's typical to switch tabs with either `Shift+Cmd+Left/Right` (Safari) or `Alt+Cmd+Left/Right` (Firefox&Chrome).

**Comment by cranes-bill** [comment]
It works, you just should check it „:heavy_check_mark:“:
**Settings** > **Keyboard Shortcuts** > :ballot_box_with_check: **Use single key shortcuts**

**Comment by skalee** [comment]
True! Polish translation was quite awkward and unclear. My pull request fixes that: #1965.

**Comment by OlafLostViking** [comment]
I didn't want to pollute the issue tracker by creating a new issue, but would do it of course, if that would be preferred over reopening an old issue.

Using the "single key shortcuts" to change tabs is nice, of course! But they won't work, when the website (just take a simple google search page) has the focus on some input field. Would it be a possibility to add "more unusual" shortcuts? Since it's a Qt browser, <kbd>shift</kbd>+<kbd>left</kbd>/<kbd>right</kbd> like konsole or <kbd>ctrl</kbd>+<kbd>.</kbd>/<kbd>,</kbd> like dolphin could be nice.

**Comment by nowrep** [comment]
@OlafLostViking Posting on closed issue is the best way to make your issue be forgotten. Please open new issue, thanks.

**Comment by OlafLostViking** [comment]
@nowrep Sure thing, thanks!
