### ISSUE TITLE
Reset from fullscreen let tabbar disappear

### ISSUE THREAD

**Issue by ShalokShalom** [QupZilla/qupzilla#1967]
I go into Youtube fullscreen, reset from it and the taskbar disappeared.
Once i go again in fullscreen and reset that, appear it back.

"dont show tabbar with only one tab" is default, so disabled.

P.S.: I expirience already some other fullscreen issues in 2.0 with QtWebEngine.

**Comment by ShalokShalom** [comment]
The funny thing is, that my own view on the issue is different from what a snapshot with spectacle shows: http://funkyimg.com/i/2bqfs.png

The white areas in Qupzilla look totaly normal for my eyes, only the tabbar is missing.

http://funkyimg.com/i/2bqhh.jpg

**Comment by cranes-bill** [comment]
I guess *Compositing manager* issue....

**Comment by ShalokShalom** [comment]
Its KWin 5.6.3 on OpenGL 3.1

**Comment by bvbfan** [comment]
I don't have this issue, same KaOS. Maybe driver bug, what is your gpu (lspci | grep -i "vga\|3d")

**Comment by ShalokShalom** [comment]
Happens also with XRender

@bvbfan your command isnt working, give me just a prompt.

[shalokshalom@cosmos ~]$ inxi -G
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: vesa) Resolution: 1366x768@60.07hz
           GLX Renderer: Mesa DRI Intel Ivybridge Mobile GLX Version: 3.0 Mesa 11.2.1
[shalokshalom@cosmos ~]$

**Comment by bvbfan** [comment]
GitHub has problems with escape characters :)
Copy output here
cat /etc/X11/xorg.conf.d/20-intel.conf
You can try new Xorg drivers
sudo mv /etc/X11/xorg.conf.d/20-intel.conf /etc/X11/xorg.conf.d/20-intel.conf_back
cat << EOF | sudo tee /etc/X11/xorg.conf.d/20-intel.conf
Section "Device"
   Identifier  "Intel"
   Driver      "modesetting"
   Option     "AccelMethod" "uxa"
EndSection
EOF
So, make logout/in, if you have problems, X don't start (only console view) don't panic type alt+ctrl+f2 login in new tty prompt
sudo mv /etc/X11/xorg.conf.d/20-intel.conf_back /etc/X11/xorg.conf.d/20-intel.conf
or just remove file
sudo rm -f /etc/X11/xorg.conf.d/20-intel.conf
then restart graphics
sudo systemctl restart sddm.service
:+1:

**Comment by bvbfan** [comment]
If you have questions -> https://kaosx.us/phpBB3/viewtopic.php?f=8&t=1470&p=7752#p7752

**Comment by ShalokShalom** [comment]
uxa give me the same error, sna holds at kernel boot

**Comment by bvbfan** [comment]
You can ask in KaOS forum, demm has coupe of Intel systems.

**Comment by nowrep** [comment]
Can you test with 1.8 and 2.0?

**Comment by ShalokShalom** [comment]
it happens with 2.0 here. You mean, if it appears in WebKit as well? Will ask some people here for this old PKGBUILD/tar.xz

**Comment by bvbfan** [comment]
You can use Arch as well on KaOS -> https://www.archlinux.org/packages/community/x86_64/qupzilla/ Be sure it's a driver issue, you can try "sna" by adding 'i915.semaphores=1' without quotes in boot parameters. F10 on boot screen and append on line start with linux

**Comment by nowrep** [comment]
It's not driver issue. Also `i915.semaphores=1` has nothing to do with `sna`, so please don't try it.

**Comment by eglefino** [comment]
Hello all,

I had problems with my last last version and could not download [every try to download I got an error message, but not a why!]. In the mean time a used Firefox and downloading was normal. Back at my best all-time browser Qupzilla I read a lot, but couldn't find any solution for this, here nobody had problems so was Trusty the pain in the ass... I could not upload either, No, it wasn't Ubuntu, no bug or so....

Today  I made with the same version (1.8.9. or like that) a new profile and looked for differences. I can not get any tabs, all I try to get the tab-manager or the menu (I tried) it did not come back... I have the same as the first writer here @ShalokShalom . I had also with my old profile that if I wanted to shut down one tab and/or one window (with circa 15 tabs in it) that the whole browser shut down.... for every problem I have or had, I have searched for solutions but could not find them, so I hope to become here some help.
regards
Amsterdam/NL

**Comment by eglefino** [comment]
I forgot to tell, that the dowload problem started after updating to 1.8.9. 
Now with the new profile I have open 6 windows (with no tabs or menu-bar: by-the-way very difficult to work with), if I want to close 1 window the message say there are more windows open (do I have to close Qupzilla for sure).... No, I want only one window to close!  So something is really wrong and maybe David can help, I haven't write any e-mails to the Qupzilla-developpers, this is my first try.

My PC: Intel i7-920 (1th gen) 12 GB ram, asus/nvidia Geforce GT 630 Rev2/2GB. Ubuntu Trusty 64-bit/kernel 33.13-86 generic working only with Cairo dock.

Can I edit Qupzilla config myself like in Firefox? The "showMenubar" is false, where can I set it to true? The tab-manager is set as always, but not working (as before). And how do I get my bookmarks back from the default-profile?
Questions enough, who has the answers.

My slogan since 2006 [the year I became bedridden] is the same as my lifestyle:
~ I'm open, honest and sincere to myself, to my partner and a little bit reserved to strangers...! ~
