### ISSUE TITLE
2.01/webseite: How to find/identify the x64 version for windows?

### ISSUE THREAD

**Issue by mabra** [QupZilla/qupzilla#1997]
Hi,

subject say all. X64 not to identify and I no longer like x84-x64 mixtures.

Thanks,
Manfred

**Comment by nowrep** [comment]
What's wrong with 32bit builds?

**Comment by mabra** [comment]
Its quite clear: They do not perform !
After Firefox was finally able to ship a x64 version, its mortale-rate shrinkf from 5 a day to 5 a week. Now, it is able to consume more then 3.x GB mem.

BTW, I just ignored my own wish and installed the new version of qupzilla. I am completely disappointed:
- in a rdp-session it does not work - black background
- for my normal work: all credentials lost

I was not happy with 1.6 (I think, this was my last version until today morning), because it regularly dies at least once a day. I use it currently only for test and it has permanent connections to all my home infrastructure. I am divertng my whole webwork over different browser for different aspects - this reduces the terror, if such a beast dies - wich is, to say for 2016 (means after about > 20 years web), the usual case. The only exception is a spy called chrome.

Sorry for my bad insights - writing a browser at 1993 would be great (ok, not more, not really fun), writing a browser after 2010 is - due to the whole marketing influence of the big players - just a big pain in the ...

Best regards,
Manfred

**Comment by Martii** [comment]
@nowrep 
So are you saying you refuse to build a 64 bit version of the Windows binary by the invalid GH label? 32 bit binaries still work on Windows however they are becoming a thing of the past because of their inefficient and lack of use of memory. Do you really want QupZilla with that additional assumed label?

**Comment by nowrep** [comment]
It's not inefficient and also works just fine with all Windows versions. I don't see any reason good enough to justify the time that I will spend on it.

**Comment by Martii** [comment]
You seem to have a misunderstanding on 32 bit versus 64 bit... even my VM is set to a larger 32GiB memory for Windows. If QupZilla is only utilizing ~3.4GiB of it's allocation of memory you are wasting my swap drive e.g. both Windows and QupZilla **are** inefficient. Being lazy on builds is a horrible precedence to establish for a project. You really should consider an additional 64 bit build. I've already picked up the OS X build for you since you don't have one... if you are that disinterested in supporting modern technologies that will be a shame.

**Comment by Martii** [comment]
Better question too... does it compile via 64 bit? e.g. since you are being complacent with builds now will it compile into a 64 bit binary with all support at 64 bit?

**Comment by nowrep** [comment]
What? :D How more allocated memory leads to wasting swap drive? :D You mean that it is a bad thing that program uses less memory?

In any case, QupZilla's processes are limited to (as you correctly stated) less than 4GB. But, QupZilla uses separate process for each web page. If a single page needs more than that, then there is most probably bug in QupZilla.

Yes, it is just matter of recompiling with 64bit compiler & libs.

For a normal user, there is no difference between 32bit and 64bit application. It looks and works the same. All 64bit Windows versions are installing the 32bit subsystem by default. so there is no inconvenience for the user.

Really, the only gain here is the fact that "it is 64bit". There is no advantage over 32bit, not performance, not security, nothing.

**Comment by Martii** [comment]
> You mean that it is a bad thing that program uses less memory?

When you run out of the allocated memory malloc/calloc/etc. *(base calls)* will pull from whatever source is available in the addressing space... in this case it would be the swap drive... I have SSD's everywhere and as you should already know they have have a limited MTBF that is lower than magnetic media. Additionally some items may not be able to swap out if they exceed the allocated data register stack. This has been the process long before I was a glimmer in my parents eyes too. ;)

> QupZilla uses separate process for each web page.

That's an improvement... however the ~3.4GiB cap is still a bottleneck.

> Yes, it is just matter of recompiling with 64bit compiler & libs.

I may spend the short 20 minutes that it takes to build that for you when I get around to it. I know builds are boring but they usually are needed for production systems. I still haven't quite figured out where QupZilla lays in the scheme of things and if OUJS should alter it's summation of this browser e.g. I don't think it's going to be production ready until a few things are addressed with administration such as this issue. I personally don't enjoy fragmenting your distribution but since you said you don't have OS X I purchased a system to help out. I know you have a Windows box so that wouldn't apply here... but I could be assuming that it's 64 bit? e.g. if you don't have the machine then that could explain your reluctance to distribute. Moz made the same mistake of not distributing a 64 bit until just recently... however I've been part of the contributor teams that released 64 bit years and years and years before it was picked up mainstream. e.g. Moz fixed their mistake.

> There is no advantage over 32bit, not performance, not security, nothing.

Uhmmm completely incorrect ... but at least you have attempted to explain it a little better for the issuer of this issue. I went 64 bit with XP back in the day and even at the ASM level it's much faster albeit a 64 bit register size. :)

**Comment by nowrep** [comment]
> I personally don't enjoy fragmenting your distribution but since you said you don't have OS X I purchased a system to help out

I appreciate that thanks, but still I didn't get any Mac build from you that I can upload at qupzilla.com.

> that wouldn't apply here... but I could be assuming that it's 64 bit? e.g. if you don't have the machine then that could explain your reluctance to distribute.

Now that you brought that up, I actually don't have currently 64bit Windows install. I use only 32bit virtual machines. But of course, that is not really a big issue, I could setup new machine.
Also there is a possibility to cross-compile to 64bit, not sure how good that work though.

> Uhmmm completely incorrect

Well, you can then compare the 64bit with 32bit QupZilla and actually benchmark it. I doubt there will be any significant difference (other than higher memory usage of 64bit build).

**Comment by Martii** [comment]
>  but still I didn't get any Mac build from you that I can upload at qupzilla.com.

https://github.com/Martii/qupzilla/releases 

> and actually benchmark it.

Especially since you are doing a browser you really should look into "thunking" as I amended in the P.S. above. It's not the only bottleneck either.

**Comment by nowrep** [comment]
> https://github.com/Martii/qupzilla/releases 

Great! Why am I seeing it only now? Uploading the build right now, thanks!

**Comment by srazi** [comment]
This seems interesting: http://www.appveyor.com/docs/installed-software#qt
Maybe it can help for Windows builds.
