### ISSUE TITLE
Provide Snap package

### ISSUE THREAD

**Issue by mhall119** [QupZilla/qupzilla#2065]
Ubuntu 16.04 ships with qupzilla 1.8.9, which means that for users who want a stable OS this will be the only version they find in the Software store for the next five years. However, if a snap package was available, it could be uploaded to the store any time to give users (not just Ubuntu users) the latest and greatest version.

**Comment by ahoneybun** [comment]
Grabbing the source and trying to do it now.

**Comment by mhall119** [comment]
I have some initial snap packaging at https://github.com/mhall119/qupzilla you can build it on Ubuntu 16.04 with "snapcraft snap" or in "snapcraft cleanbuild" if you'd rather do it in an LXC container.

It builds and runs, but doesn't quite work. It's missing icons and the rendering is bad. At this point I need help from somebody who knows the qupzilla code to make further progress.

**Comment by ahoneybun** [comment]
I think it looks more like a QtWebEngine issue. But how did you build it on 16.04?

**Comment by Martii** [comment]
@mhall119 
Just a suggestion... some integration if this is merged into the upstream master you may want to [create a branch on your fork](https://help.github.com/desktop/guides/contributing/making-changes-in-a-branch/). Since you are committing to your master that can impede some `git` operations.

As Ubuntu is my least perused \*nix platform it would be helpful for observers to have some linkage to what "snap" is for starters. My main distro has no publicly advertised version of this and unclear if **all distros** have this support easily integrated. Obviously there are search engines however with the ever changing build systems out there and publication systems too... it is best imho to give a little reference for the newcomers and even those who have been around.

Thanks.

**Comment by cranes-bill** [comment]
@mhall119
You should use: `DEFINES+=NO_SYSTEM_DATAPATH`

**Comment by mhall119** [comment]
I tried setting NO_SYSTEM_DATAPATH but it's still looking at /usr/share/qupzilla/ for things like themes, is there something else that needs to be set?

**Comment by nowrep** [comment]
@mhall119 No, that is enough. How did you set it? `qmake DEFINES+=NO_SYSTEM_DATAPATH` should work.

**Comment by mhall119** [comment]
That's what I did, let me clean up my environment to make sure it's not something leftover from a previous attempt

**Comment by nowrep** [comment]
Falkon is now available as snap package.
