### ISSUE TITLE
JavaScript should not be disabled for Web Inspector

### ISSUE THREAD

**Issue by GreenLunar** [QupZilla/qupzilla#2103]
When turning off JavaScript from preferences dialog, Web Inspector is always unusable, even when temporarily turning on JavaScript with a StatuBar Icon.

QupZila 1.8.9

**Comment by nowrep** [comment]
There's nothing to be done in case of QtWebKit. In QtWebEngine builds the web inspector is a big hack currently and also I've been thinking of completely removing the option to turn off javascript as javascript is essential for a lot of features.

**Comment by GreenLunar** [comment]
> I've been thinking of completely removing the option to turn off javascript as javascript is essential for a lot of features.

Disabling JS matters, since many websites do not have proper JS scripts.

**Comment by Martii** [comment]
> I've been thinking of completely removing the option to turn off javascript as javascript is essential for a lot of features.

I would be disappointed seeing a browser that doesn't allow this option. On the flip side of the coin some JavaScript is invasive and downright irritating which is why my Moz browsers always have NoScript, per domain, per protocol enabled allow/block list. If that extension didn't exist then the base browsers can disable it globally which could be cumbersome but still a necessity.

As far as debugging goes whether Userscript or base web programming it would be useful to test with it off/on and not kill any feedback but seems like a pitfall of QtWebKit at the moment.

**Comment by Chiitoo** [comment]
While it is an unfortunate fact that JavaScript is needed for many sites to be useable (and QupZilla itself uses it for things such as Speed Dial I think?), I, too, feel it would be unfortunate if there was no option to completely disable it.
