### ISSUE TITLE
spellcheck   only works with *.bdic files in /usr/bin/qtwebengine_dictionaries/

### ISSUE THREAD

**Issue by stefonarch** [QupZilla/qupzilla#2195]
As subject: when *.bdic file is present in both there are present twice  in the "spell check"  preference dialog window  but only the one in  /usr/bin/qtwebengine_dictionaries/ actually works.

EDIT: testing with two language (it_IT, en_US) there is no way to use the latter  and selecting is tricky because both get highlighted.

EDIT2: with 3 languages (de,en,ti) all seem working and no issue with highlight: I see there are not exclusive sorry.

 arch and  qupzilla-git v2.1.0.r0.g4062473e-1

Related: maybe creating the empty directories on install?

**Comment by nowrep** [comment]
So, the actual bug is that the languages may be duplicated in the language list. Also, it should be possible to re-order the selected languages (it's not possible now).

As with the directories, it's a tricky because QtWebEngine does not allow to change those directories and in case of Linux installs, both directories are not user-writable.

**Comment by stefonarch** [comment]
> So, the actual bug is that the languages may be duplicated in the language list.
Duplicated  when present in both directories yes, but the bug is about that the  *.bdic files present in /usr/share/qt/qtwebengine_dictionaries/ does not work at all here.

**Comment by nowrep** [comment]
> *.bdic files present in /usr/share/qt/qtwebengine_dictionaries/ does not work at all here.

That is QtWebEngine bug then, as it says in doc that it will load directories from there.
