### ISSUE TITLE
Running qupzilla remotely?

### ISSUE THREAD

**Issue by jamesqf** [QupZilla/qupzilla#2241]
I'm trying to run qupzilla (2.0.1) remotely, but it doesn't seem to work.  It starts, and the main window frame is drawn, but then nothing more happens.  Other X programs seem to work just fine when started the same way - from a remote xterm command line with ssh X forwarding enabled.

The remote machine is running OpenSuse 46.2 (I think - the latest version as of a couple months ago), and qupzilla works ok when run locally on it.  (Except for the issue below.)  Local machine is OpenSuse 13.1. and I've been running qupzilla 1.8.9 there for a year or more.

The problem I'm trying to resolve is that the IRS on-line tax filing site wants something called "session cookies" which 1.8.9 doesn't seem to have.  2.0.1 apparently does, but it uses different fonts which are quite hard on my eyes.  I'm trying to figure out whether this is an issue with the OS, X, or the display hardware on that machine.  (Upgrading the 13.1 machine isn't an option right now, as the 46.2 uprgrade seems to have broken a few small but important to me things.)

**Comment by Martii** [comment]
> It starts, and the main window frame is drawn, but then nothing more happens.

Possibly related to #1943 although your issue is xterm forwarding in Linux... I'll see if I can run it from the AppImage on a remote and confirm later today through SSH.

> 2.0.1 apparently does

Try 2.1.1

> I'm trying to figure out whether this is an issue with the OS, X, or the display hardware on that machine.

Before I do anything more on this... please clarify what your host is and what your guest is. e.g. from what platform to what platform as the "OS X" bit is a bit unclear.

**Comment by jamesqf** [comment]
Oops, I didn't see that "OS, X" might be mistaken for a different operating system than the Linux I'm using :-)

To clarify, I'm using OpenSuse Linux on both machines.  The one I'm viewing on is 13.1, the one qupzilla is running on is 42.2.  (Don't ask me why on Earth their version numbering jumped from 13 to 42 :-() X of course is XWindows.

**Comment by jamesqf** [comment]
Re "Try 2.1.1", where can I download this?  The qupzilla download page has an OpenSuse link, which says "(.rpm) can be downloaded by clicking on links below", but there are no links below. (Using 2.0.1: 1.8.9 shows links, but they don't actually do anything.)

**Comment by Martii** [comment]
> OpenSuse link, which says "(.rpm) can be downloaded by clicking on links below", but there are no links below.

Good point. May have to compile it yourself... that's what I get to do as soon as a few spare minutes appear. Any thoughts on why the linkage is missing @nowrep ?

>  OpenSuse

I only have access to OpenSUSE Leap since the VM software I use routinely crashes with TumbleWeed. So keep that in mind when that point is reached.

And sorry I haven't had time to diagnose this just yet to see if xterm is having display issues with X11 forwarding. Leap is considered "stable" and "TumbleWeed" is considered "bleeding edge"... so there may be issues with "unstable" releases.

**Comment by Martii** [comment]
You might be able to use the AppImage link too under "Other Linux".

**Comment by jamesqf** [comment]
No hurry on the diagnosis.  I'm going to try compiling 2.1.1 myself, but I have to install a bunch of qT stuff first.  I don't really do GUI programming, so never needed it before.  And of course there's always the lack of those few spare minutes...

I am using the "Leap" version of OpenSuse on that machine.  I'm not a big fan of working on the bleeding edge, or having automatic updates break things.  Which is why all my other machines are still on 13.1 :-)

**Comment by Martii** [comment]
> OpenSuse 46.2 ...  OpenSuse 13.1

FWIW I do seem to recall that Qt KDE/Plasma versions have to be the same in order for X11 forwarding to work properly since the host libs are used... at least according to my distro and a vague recollection of a reading a while back. Finally got the compile done in the VM of the current HEAD... so I should be able to test something soon hopefully. Have to reconfigure my test box next but it might be early next week before I can do that.

**Comment by jamesqf** [comment]
Yes, I think 42.2 is the latest (supposedly - it has bugs :-() stable version.

Could you perhaps point me to some better compile instructions than are contained in the source tarball?  After installing the latest (per OpenSuse's package manager) versions of qT &c, and figuring out that the required qmake is installed in an oddball place rather than one of the standard executable directories, I finally started a compile - only to immediately get the discouraging message "Project ERROR: Qupzilla requires at least Qt 5.7!".  

How the heck am I supposed to install something that's newer than new?

**Comment by cranes-bill** [comment]
Try [Appimage](https://www.qupzilla.com/download#linux) first, where you don't need to install Qt!

**Comment by Martii** [comment]
> After installing the latest (per OpenSuse's package manager) versions of qT &c...

https://wiki.qt.io/Install_Qt_5_on_openSUSE is more up to date and contains the maintenance tool to install older and newer versions of Qt. The instructions also include the meta package zypper.

> How the heck am I supposed to install something that's newer than new?

Most package repositories are older than current releases.

> better compile instructions...

Since the global `/opt/Qt/...` is used for installation with those instructions you call `qmake` using the full absolute path to your platform. Under TumbleWeed if I set the `PATH` environment variable to the `bin` directory of Qt it definitely hoses the VM that I use since OpenSUSE looks for that on boot for some reason.  Using the absolute path to `qmake` will initialize `make` to find the appropriate libraries for whichever version you want to compile against. 

I also usually have to use the export flag of `export USE_LIBPATH="/usr/lib64"` before all of it.

**Comment by cranes-bill** [comment]
> I'll be trying that at well ... not sure if 13.x has AppImage support or not since it's older.

Seems **openSUSE 13.2** uses **glibc-2.19**, which should be enought for Qt version in AppImage.

**Comment by jamesqf** [comment]
Tried the AppImage version, but it doesn't work (on OpenSuse 42.2).  Gives an error message "Fatal: this application failed to start because it could not find or load the Qt platform plugin "xcb" in "/tmp/mount/_Dlc04i/plugins/platforms"".

I have to admit I'm pretty well lost here.  From the little bit I read about AppImage before downloading this one, it seemed that is was just a fancy name for a normal (to me, anyway) statically-linked executable.  But obviously I'm missing something...  

(And for another puzzlement, why the heck does the AppImage link above run Firefox to do the download?  (On my 13.1 system.))

**Comment by jamesqf** [comment]
And another oddity: Just for curiousity's sake, I tried running the AppImage on my 13.1 system, where it runs (unlike on 42.2) but thinks there's no internet connection.  But since I'm writing this on the same system (using 1.8.9) without rebooting or anything, the connection obviously is working...

**Comment by cranes-bill** [comment]
@jamesqf, make sure you don't have other QupZilla executable, running in the same time when you trying Appimage!

>Gives an error message "Fatal: this application failed to start because it could not find or load the Qt platform plugin "xcb" in "/tmp/mount/_Dlc04i/plugins/platforms"".

Something was wrong here (if you correctly quoted it). Should be `/tmp/.mount_Dlc04i/` instead

**Comment by nowrep** [comment]
I don't think you can remotely run GL apps with X.

**Comment by Martii** [comment]
@nowrep 
> I don't think you can remotely run GL apps with X.

As I stated it uses the hosts libs including video... been a while since I've done X11 forwarding though as I usually just VNC the whole screen. If you want an external reference there's one that kicked up in a search at https://arrayfire.com/remote-off-screen-rendering-with-opengl/

@jamesqf 

> why the heck does the AppImage link above run Firefox to do the download? (On my 13.1 system.

MIME association usually... depends on if the package or build registers it. When I get back *I'm still going to be retesting this* as it's good experience for seeing what does and what doesn't work. I've encountered one issue with the AppImage on my main distro although it doesn't crop up too much... but none-the-less you should install the core of Qt if possible as the instructions describe. They went through a major revamp to get multiple versions installed on every platform so usually distro packages are isolated to their packages and development should use the unified installer.

Btw created QupZilla/qupzilla.com#43 for the missing download links for SUSE.

**Comment by Martii** [comment]
@jamesqf 
I'm going to need to spend some quality time with Tumbleweed... the default installation on my test box is attempting to write to UEFI *(EFI)* when BIOS says do not... which is currently a security risk. e.g. I won't be able to test anything using that method until that is resolved. Sorry. I'll see if my distro works as expected with it.

**Comment by jamesqf** [comment]
I've been trying to compile from source. Got the Qt stuff installed, and qmake runs, but now I've run into yet another problem.  The make quits with a message "xcb/xcb_atom.h: No such file or directory" while trying to build "browserwindow.o".  I have downloaded and built (what I think is) the latest xcb package (libxcb-1.11.1), and there is no xcb_atom.h file in it.

Any idea where I could find this, or what else I could be doing wrong?

**Comment by cranes-bill** [comment]
In other distributions that package is calling [lib]**xcb-util-dev**[el], but in Open suseeeee......

**Comment by Martii** [comment]
@jamesqf 
It should be installed package wise ... try the Qt instructions at https://wiki.qt.io/Install_Qt_5_on_openSUSE . As a starting point it's best to try the package repositories first before building from source... then if something specific is needed you compile source by hand.

**Comment by jamesqf** [comment]
I did try re-installing the xcb package (or rather, packages - there seems to be a whole page of them) via OpenSuse's installer.  It was installed anyway, but I tried again just in case something was missed.  And was the same version as the xcb source I then downloaded to see it the file would be in the source, or made during the build.  

I did use the Qt installer per those directions for the Qt install, and that part seems to work - at least qmake completes successfully.  It's the missing file in xcb that seems to be the problem with the subsequent make.

**Comment by cranes-bill** [comment]
[13.2](https://ftp.gwdg.de/pub/opensuse/distribution/13.2/repo/oss/suse/x86_64/xcb-util-devel-0.3.9-11.1.2.x86_64.rpm)   
[42.2](https://ftp.gwdg.de/pub/opensuse/distribution/leap/42.2/repo/oss/suse/x86_64/xcb-util-devel-0.4.0-2.3.x86_64.rpm)

**Comment by Martii** [comment]
@jamesqf 

> "xcb/xcb_atom.h: No such file or directory"

This was located under a different development package in my virtual machine *(VM)* of ROSA distro... so perhaps 13.1 has it in a different `xcb-`...

I just installed the full development compliment with my VM distro so I didn't pin it down to a specific package name other than `xcb` and with `dev` and `64` for 64 bit.

**Comment by jamesqf** [comment]
Well, I got it to compile, finally.  The xcb_atom.h file was hidden in one of the additional packages, as were some other files for OpenSSL &c.  (For the record, I'm doing the compile &c on OpenSuse 42.2.  13.1 is my working machine that won't get touched until I'm sure that everything in 42.2 is working correctly - which on current progress may be never :-()

Now I have another problem.  When I try to run the new qupzilla executable, it says

[code] 
/usr/lib64/libQt5Core.so.5: version `Qt_5.8' not found (required by qupzilla)
/usr/lib64/libQt5Core.so.5: version `Qt_5.8' not found (required by /opt/Qt/5.8/gcc_64/lib/libQt5Positioning.so.5)
/usr/lib64/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /opt/Qt/5.8/gcc_64/lib/libQt5Positioning.so.5)
[/code]

The Qt installer puts the library files in /opt/Qt/5.8/gcc_64/lib. I've set the LD_LIBRARY_PATH to that, but it appears that the executable somehow has gotten a hardcoded path.  Any suggestions?

**Comment by Martii** [comment]
@jamesqf 

> When I try to run the new qupzilla executable, it says ...


Did you try exporting that environment variable I mentioned [up here](https://github.com/QupZilla/qupzilla/issues/2241#issuecomment-285779546) before all other commands?

The abbreviated [BUILDING.md](https://github.com/QupZilla/qupzilla/blob/master/BUILDING.md) instructions tailored to OpenSUSE and what you have told me of your Qt installation:

``` sh-session
$ make distclean
$ echo "Optionally do the `export` mentioned above but usually done on 64 bit platforms"
$ /opt/Qt/5.8/gcc_64/qmake
$ make
$ sudo make install
$ qupzilla
```
... the last command is where you might be having the missing .so file.

**Comment by jamesqf** [comment]
OK, got that one fixed - my bad, had LD_LIBRARY_PATH directories in the wrong order.  Now on to the (sigh) next problem.  qupzilla now starts, but after a second or two it quits with the message

QupZilla: 1 extensions loaded
qupzilla: symbol lookup error: 
qupzilla: undefined symbol:
_ZN15MainApplication13setProxyStyleEP10ProxyStyle

There are a lot of references to "MainApplication" in the source, but I don't see anything like "MainApplication13...".  Is it perhaps c++ or Qt doing some name mangling?

**Comment by Martii** [comment]
> "MainApplication" in the source, but I don't see anything like "MainApplication13 ... Is it perhaps c++

While I don't have access to the system I would have to say those are object link references in the linker for CPP. Anyhow... I've never had to set an environment variable for `LD_LIBRARY_PATH` in my travels with QupZilla under Leap *(Tumbleweed crashes if I do that at all other than the basic ones that QupZilla offers)*. The above steps I posted is all that is really needed as QupZilla and Qt appear well configured with a few bumps here and there minus KDE integration or Gnome flags since I didn't include those.

> symbol lookup error

Can mean a few things from my experience. 1. Hardware corruption 2. Linker error with incompatible libraries 3. Debugging when it's not in production mode. 4. User error

Do have some questions to throw at you:
1. Is this a dual boot system?
2. If not have you performed an intensive system diagnostic e.g. the physical realm of the machine(s)?
3. Running any third party non-approved by the manufacture hardware that may make the system(s) unstable?
4. Are you exceeding the build process for QupZilla e.g. are you trying to do something different than what is currently in Qt/QupZilla?

Anyhow... most of these questions are beyond the normal scope of QupZilla so you might want to back track and move towards the root of the Linux tree for some possible answers.

I understand that you'd probably like all the answers here but time is running short for this. I've shared my experiences with Leap and even Tumbleweed. It's possible to get it to work with QupZilla but it's not my preferred distro due to instabilities. If you can document your entire processes I can look over it but these random guesses aren't very productive imho. Sometimes one just has to wait and perhaps find the time to figure out what's next. :)

**Comment by Martii** [comment]
So  here's the test results on same distro to same distro different nVidia GPU vs Intel APU *(same with switch and without)*:

``` sh-session
$ ssh -fX remotely.localdomain qupzilla --disable-gpu
user@remotely.localdomain's password: 
[user@locally ~]$ libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
```
... so basically the label assigned here is accurate **for the time being** albeit it may be possible to render as I posted with that link above, or similar.

Some things to be done at some point
* There are a few articles around the web that can be searched for regarding proprietary nVidia drivers breaking openGL linkage. Check linkage.
* Most platforms have some sort of openGL compatibility setting e.g. 2.0 or 3.1 or whatever... match those and see what happens.
* Try out XCFE for X11 displays between both machines to see if that works as a short term solution.

**Comment by jamesqf** [comment]
Tried following your instructions above, with a couple of (I think) minor deviations:

  1) I have Qt 5.8 rather than 5.7
  2) Since I run tcsh, I use setenv instead of the bash export to set USE_LIBPATH
  3) I used make -j 4
  4) I ran the executable from the development bin directory, since I don't want to overwrite the older_but_working version I have.

I get the same result, undefined symbol _ZN15MainApplication13setProxyStyleEP10ProxyStyle

I suppose I can try installing Qt 5.7 when I next get a few minutes.

For the questions a few messages back,

  1) It is a multiple boot system
  2) I haven't done any hardware diagnostics on it, but it seems to run quite well (other than a few minor glitches that I think are due to the new OS.)
  3) It doesn't have any non-standard hardware, other than an NVidia graphics card.  
  4) I've installed Qt/qupzilla per your instructions, and haven't changed any of the defaults.

**Comment by Martii** [comment]
> ... since I don't want to overwrite the older_but_working version I have.

You can always checkout that particular version in case you aren't happy with the bug fixes.... then recompile that version if you need to fall back. Not sure if OpenSUSE has a "snapshot" application like mine to restore the previous state too.

> I get the same result...

Here's a thought... `# zypper se virtualbox` on the existing target and see if you can tinker in the VM if you don't have a snapshot function native to OpenSUSE. VirtualBox does have a snapshot feature so you can roll back to a prior point. Been wondering if I could do this myself with my own distro... so I'll add that to the next list for my test rounds.

> I ran the executable from the development bin directory, 

When I last ran it from the bin folder I got all kinds of errors with `gdb`. So I just installed the current HEAD and those issues disappeared when running with the GNU debugger.. I would say that the bin folder may not reference the Qt libraries fully until `sudo make install` is done first is an educated guess.

> I have Qt 5.8 rather than 5.7

So do I... I rebuilt that VM a few days back and appended to [up here](https://github.com/QupZilla/qupzilla/issues/2241#issuecomment-287286260).

**Comment by jamesqf** [comment]
OK, doing a "make install"... and it seems to work!  That's really strange: I've never run into anything that had to be installed in a particular directory before.

Unfortunately, it still does the same thing when I try to run it remotely - draws the window frame (empty and transparent inside), and gives an error "libGL error: failed to load driver: i965".

So I guess it's either with the semi-legible fonts, or get into trying to set something better.  But it seems like there are literally thousands of choices...  Though now that I think on it, the fonts should be set by my user CSS...

Anyway, thanks much for all the help.
