### ISSUE TITLE
Problems loading pages

### ISSUE THREAD

**Issue by fdservices** [QupZilla/qupzilla#2279]
Sorry for the brief heading.
Qupzilla Application version 2.1.2
QtWebEngine version 5.8.0
Linux acer 4.10.5-1-ARCH #1 SMP PREEMPT Wed Mar 22 14:42:03 CET 2017 x86_64 GNU/Linux

Try to view, for example, http://www.mr-bricolage.fr/?magasin=Marconne 
On initial load I often get "Failed loading page", on "Reload Page" it may or may not load correctly.
Try to search for a product (Recherchez un produit, une reference, une marque ...) e.g. tuyau
On enter (or click on spyglass) I get "Failed loading page", on "Reload Page" it goes back to the home page.

I hope this makes sense - thanks

Andrew

**Comment by iondissonance** [comment]
All works, can't reproduce. QupZilla 2.1.99 (2.1 branch) with Qt 5.8 on Opensuse Leap 42.2

**Comment by nowrep** [comment]
"Failed loading page" means the web process crashed.

**Comment by fdservices** [comment]
@iondissance: Thank you, just in case I tried with a new profile, with similar results.

@nowrep: Yes, I thought so.

Andrew

**Comment by kevinhendricks** [comment]
Ran into same thing with Qupzilla 2.1.2 on Mac just downloaded and installed but only for sites that do not support  https.

For example: try typing the following address to load a ebook author related website: (notice the use of http not https).

http://www.mobileread.com

It will load but it will show up in the address bar as:

https://www.mobileread.com

Now as a result of that all reloads of that page or any attempt to reach an internal link such as the Forums (http://www.mobileread.com/forums) all fail as they are all improperly prefaced with https  instead of just http somehow by QupZilla.

This simple site functions just fine in all other browsers.

**Comment by AcarBurak** [comment]
Same here on Arch with webengine 5.8.0-4. Yet opening it (forums page, for instance) in a new tab works.

**Comment by kevinhendricks** [comment]
Yes, if you manually load any address and properly preface it with http vs https you can access the forums in a new tab.  You just can't get there by clicking a link from the main page as QupZilla tries to load https://www.mobileread.com/forums instead of the correct http://www.mobileread.com/forums.

**Comment by AcarBurak** [comment]
@kevinhendricks, here, just middle clicking forums link opens that page in a new tab successfully with the address https://www.mobileread.com/forums/.

**Comment by AcarBurak** [comment]
Same with https://ultimatemotorcycling.com/riding-style/adventure-off-road/adventure-dual-sport-motorcycle-reviews/page/2/.

Reloading the page or clicking the 3 (third page at the end) or clicking -> (next page at the end) fails, but middle clicking 3 or -> works, the next page opens in a new tab.

**Comment by kevinhendricks** [comment]
Confirmed .. somehow forcing a link to open in a new tab allows the connection to succeed.  
Strange

**Comment by Martii** [comment]
@kevinhendricks 

Re:

> Ran into same thing with Qupzilla 2.1.2 on Mac just downloaded and installed but only for sites that do not support https.
>
> For example: try typing the following address to load a ebook author related website: (notice the use of http not https).
>
> http://www.mobileread.com
>
> It will load but it will show up in the address bar as:
>
> https://www.mobileread.com
>
> Now as a result of that all reloads of that page or any attempt to reach an internal link such as the Forums (http://www.mobileread.com/forums) all fail as they are all improperly prefaced with https instead of just http somehow by QupZilla.

Intermittently reproducible using back history button. If I click on the forums linkage it did reload the first time though. Mac OS X 10.12.3 *(Sierra)* and 686ad7eee2 ... however bringing this a little more locally I've noticed the inverse applied at https://github.com/QupZilla/qupzilla.com/issues/43#issuecomment-287600225 with OpenSUSE linkage. e.g. not redirecting from http to https.

**Comment by fdservices** [comment]
> Confirmed .. somehow forcing a link to open in a new tab allows the connection to succeed.

Confirmed

**Comment by nowrep** [comment]
Works with QtWebEngine 5.9
