### ISSUE TITLE
Slack doesn't work on qupzilla

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [QupZilla/qupzilla#2323]
When I want to use slack (www.slack.com) it warn me "We are no longer supporting this version of your browser, so you’ll need to update it to keep using Slack."

**Comment by jamesqf** [comment]
Your can use the User Agent Manager (in Preferences->Other) to set the user agent string (= browser & version) that web sites see.  There are several built-in strings: for me, using the "Mozilla/Gecko/Firefox" one seems to work when web sites complain about my default Opera one.  (Though the Opera one gives better visuals, IMHO, which is why I use it.)

**Comment by ayhanyalcinsoy** [comment]
Tanks! Your advise works. How can I set selected option as default when I build qupzilla?

**Comment by jamesqf** [comment]
I don't know how you would do that.  However, I think the choice is sticky, so you only need to do the selection once if you like it.

**Comment by nowrep** [comment]
Changing user-agent fixes this issue.
