### ISSUE TITLE
Control+F doesn't work with Qt 5.9

### ISSUE THREAD

**Issue by AcarBurak** [QupZilla/qupzilla#2351]
In Arch Control+F only works in Speed Dial though I haven't changed the char encoding which is ISO-8859-1. If I change the encoding it doesn't work in Speed Dial as well.

**Comment by nowrep** [comment]
49eb9a862e4441670339b8075318e16070f0183e

**Comment by AcarBurak** [comment]
Thank you.

**Comment by Pyntux** [comment]
Yes, does not working under Arch linux... I tried to use new profile, but same issue.

**Comment by Pyntux** [comment]
I realized these past few days that option ctrl + F works sometimes but not on all pages. if does not work the first time on a web page (any) then it will not work the entire session until restart app. If works after start on any web page, than it will works for any web page...

**Comment by Chiitoo** [comment]
Pyntux,

It probably works when you have the 'navigation toolbar', or the 'web search bar' active, and this was fixed by the commit nowrep pointed out (49eb9a862e4441670339b8075318e16070f0183e).

If it's something else, it's something else, though.  :]

The commit is not in the latest release though, so one would need to either wait for the next release (which might come during this passing month), patch it in, or build from the master branch at or after the point in time the change was implemented.
