### ISSUE TITLE
On Whatsapp Web nothing happens when trying to load a file

### ISSUE THREAD

**Issue by Lombress** [QupZilla/qupzilla#2373]
1. Get into https://web.whatsapp.com/ and connect a phone
2. open a chat and click on the paper clip in the top-right corner
3. try to click on one of the buttons ("photo or video", "document", "camera", "contact")
4. nothing happens

On Firefox it works

Opensuse Leap 42.2, Qupzilla 2.0.1, QtWebEngine 5.6.1 (patched version from this repo [https://build.opensuse.org/package/show/home%3Amephisto%3Abranches%3AopenSUSE%3ALeap%3A42.2%3AUpdate/libqt5-qtwebengine](url) )

**Comment by nowrep** [comment]
You should use newer QtWebEngine, 5.6.1 is very old.

**Comment by Lombress** [comment]
Qt Version in Opensuse 42 is 5.6, I don't think I can upgrade QtWebengine without upgrading lots of other packages, and I don't know if my system would still be stable after changing repository for so many packages. And I need the patched version to watch H264 videos (as you can see here: https://github.com/QupZilla/qupzilla/issues/2361), but there's no patched QtWebengine of a newer version for Opensuse 42.2, only for Tumbleweed, but I need a stable system and a stable browser as lightweight as possible

**Comment by Vistaus** [comment]
@Lombress I understand your problem, but you have to understand that QtWebEngine hasn't really matured yet. Even the current stable version, 5.9.1, still isn't as mature as it oughta be. But 5.6 esp. is so old and immature that upgrading is truly necessary. Normally it's not always bad to use older version, but with the current state of QtWebEngine, one really has to upgrade to the latest version always in order to have the at that time best possible experience.

**Comment by Lombress** [comment]
But I CAN'T upgrade QtWebengine in Opensuse. Well, this and DRM are the only things that don't work, but I have other programmes to do that. Or I will try with Appimage or something like that...

So, if you are sure that the upload buttons of Whatsapp Web work with newer QtWebengine, I will close this issue. It seems nobody has tried yet

**Comment by Vistaus** [comment]
I know that you can't upgrade QtWebEngine, I was just trying to explain to you the situation regarding the state of (old) QtWebEngine versions.

I'm running QtWebEngine 5.9.1 and I'll try WhatsApp Web (I don't have WA, but my mum has so I'll use her account) and see if the issue is still present.

**Comment by Vistaus** [comment]
GOOD NEWS: with QtWebEngine 5.9.1, it works as expected! See my screenshots down below (I edited them a tiny bit because of privacy reasons).

![screenshot from 2017-07-28 21 38 26](https://user-images.githubusercontent.com/1716229/28733860-5a14eee4-73de-11e7-86f4-10cae790c117.png)

![screenshot from 2017-07-28 21 38 53](https://user-images.githubusercontent.com/1716229/28733861-5a167fca-73de-11e7-9c36-6512b33f0372.png)
