### ISSUE TITLE
Flash!!!

### ISSUE THREAD

**Issue by kingbigdave** [QupZilla/qupzilla#2376]
Hi,
Ive just downloaded Qupzilla and installed it. It seems a great browser and one I'd like to persevere with.

The first big problem I have come across is flash not working.  I am using Windows 7. I have flash installed and all the other browsers work fine. 

I cannot see how to set up flash with Qupzilla which means I can't watch BBC iplayer or TIZ cycling (Tour de France).  

It raises 2 questions:
1.   Does Flash work with Qupzilla and if so how do I fix it?
2.   Is Qupzilla compatible with HTML 5?

Any help would be greatly appreciated

Thanks

Dave

**Comment by Chiitoo** [comment]
Teegrins, kingbigdave!

1. I'm not sure about using plain adobe-flash as is, but the “pepper” flavour of it should work (I've not tried, as I've not had the need for flash for years now).  The files needed for it are not shipped by default due to their proprietary nature, however, and you'll probably need to work on it a little bit.

- Here is a great blog post explaining some of the details: https://blog.qt.io/blog/2016/06/03/netflix-qt-webengine-5-7/

- I'm not familiar enough with the QupZilla builds for Windows to be able to say if any of it will work without compiling it from source, with the required changes applied (I do believe at least the pepper plug-in should work).

2. Yes.

This all expects you to be using QupZilla version 2 or higher that makes use of the QtWebEngine, instead of the QtWebKit.

Welcome to QupZilla!

**Comment by nowrep** [comment]
Proprietary codecs are not enabled on Windows builds, otherwise everything should work fine.
