### ISSUE TITLE
WhatsApp Web not working Qupzilla

### ISSUE THREAD

**Issue by jtechpro** [QupZilla/qupzilla#2399]
I am running the Qupzilla version 1.8.9 with Webkit version 538.1
When I try to open web.whatsapp.com I am redirected to the following page:

https://web.whatsapp.com/browsers.html?missing=cryptoSha256,cryptoAesCbc

From the above URL it is clear that cryptoSha256 and cryptoAesCbc are missing in Qupzilla. It is not a problem of the user agent string as is mentioned in the issue #1779 (User-agent update) which is a way too old.

Fix this soon. On my PC qupzilla alone works smooth compared to other browsers!

**Comment by nowrep** [comment]
Please update to QupZilla 2.x

**Comment by jtechpro** [comment]
I am running Linux Mint 18 Xfce based on Ubuntu 16.04 LTS (Xenial). The PPA doesn't seem to have 2.x version, the latest is 1.8.9 only. How can I update?

Reference: [Qupzilla Official PPA](https://launchpad.net/~nowrep/+archive/ubuntu/qupzilla)

**Comment by Martii** [comment]
@jtechpro 
This is for a slightly older Linux Mint distro but give this a whirl for Qt at http://tutorialforlinux.com/2016/02/10/how-to-install-qt5-sdk-on-linux-mint-17-3-rosa-easy-visual-guide/ with the Qt Unified Installer. A [stackexchange response](https://unix.stackexchange.com/questions/272412/how-to-install-latest-stable-release-of-gcc-in-linux-mint/272421#272421) claims C++ is preinstalled so that leaves the xcb libs and openssl to check for bare minimums from https://github.com/QupZilla/qupzilla/blob/master/BUILDING.md#linux--unix
