### ISSUE TITLE
Option to disallow 3rd party fonts

### ISSUE THREAD

**Issue by nekoswag** [QupZilla/qupzilla#2445]
It would be neat if QupZilla/Falkon had an option to disallow 3rd party fonts on websites, like Firefox does.
This could help bring down page load times and improve privacy.

**Comment by nowrep** [comment]
What do you mean with "3rd party font"? If all webfonts, you can just block them with `*$font` adblock rule.

**Comment by nekoswag** [comment]
I tried that, but it doesn't work, a test site like 
https://typecast.com/preview/google
still shows them.

Only blocking font domains directly works.
abp:subscribe?location=https://secure.fanboy.co.nz/fanboy-antifonts.txt&title=Anti-font%20Tracking

**Comment by andr222** [comment]
I like to use the same font for all web page content.
It is not about speed (since many fonts are installed by default on my distro), but about clarity of display.
I'm not trying to see a pretty picture, but want a page easy to read without ambiguity.
Blocking font domains can't work, since many ambiguous fonts are already installed.

**Comment by nowrep** [comment]
`*$font` AdBlock rule should be fixed then.
