### ISSUE TITLE
Can't compile with Qt 5.10

### ISSUE THREAD

**Issue by antonio-rojas** [QupZilla/qupzilla#2487]
qmake function lessThan compares floats, not version numbers, so 5.10 < 5.8. Trying to compile qupzilla with Qt 5.10 beta gives
Project ERROR: QupZilla requires at least Qt 5.8!

**Comment by Chiitoo** [comment]
Indeed, 'versionAtLeast()' could perhaps be used instead, but I didn't look into backward compatibility, so maybe there needs to be more than one test (or bump up the Qt requirement...)?

The build will likely fail after that, too, due to content generated into 'ui_searchtoolbar.h' during the build.  I only tried with 5.10.0-alpha, though, and I'm not sure anything changed for 5.10.0-beta with regards to this.

It is possible to complete the build by changing 'QLatin1String' to a 'QString' or 'QLiteralString' in the spots it fails, but I think I had some runtime issues, including crashes, and went down to 5.9.2 for the time being.

Might be time to try again soon.

**Comment by pavbaranov** [comment]
With #1408b56 it's still impossible to build Qupzilla agaist of Qt5.10 (beta4). 
And it worse, that QupZilla on Qt5.10 is very unstable. 
I'll put another thread with logs of crashes.
